"""
report_generator.py — QueryPilot
----------------------------------
Converts raw agent research into a structured, professional report
using Google Gemini as the formatting engine.
"""

from __future__ import annotations

import re
from datetime import datetime
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.schema import HumanMessage, SystemMessage


REPORT_SYSTEM_PROMPT = """
You are QueryPilot's Report Writer — an expert technical writer.
Convert the provided research notes into a clean, structured research report.

Follow this EXACT structure (use these exact section headers):

---

# {TITLE}

**Topic:** {topic}
**Generated by:** QueryPilot — Autonomous AI Research Agent
**Date:** {date}

---

## Introduction

[2-3 paragraph introduction covering what the topic is, why it matters, and what this report covers]

---

## Key Findings

- **[Finding Title]:** [2-3 sentence explanation with specific details]
- **[Finding Title]:** [2-3 sentence explanation with specific details]
- **[Finding Title]:** [2-3 sentence explanation with specific details]
- **[Finding Title]:** [2-3 sentence explanation with specific details]
- **[Finding Title]:** [2-3 sentence explanation with specific details]

---

## Challenges

- **[Challenge Title]:** [explanation of the obstacle or problem]
- **[Challenge Title]:** [explanation of the obstacle or problem]
- **[Challenge Title]:** [explanation of the obstacle or problem]

---

## Future Scope

- **[Future Trend]:** [explanation of what's coming]
- **[Future Trend]:** [explanation of what's coming]
- **[Future Trend]:** [explanation of what's coming]

---

## Conclusion

[2-3 paragraph conclusion summarizing key takeaways and overall significance]

---

*Report generated by QueryPilot · Powered by Google Gemini & LangChain*

---

STRICT RULES:
1. Use ONLY information from the research notes — no hallucination
2. Formal, academic tone throughout
3. Bold titles on every bullet point
4. Introduction and Conclusion must be prose paragraphs, NOT bullet points
5. Minimum 5 Key Findings, 3 Challenges, 3 Future Scope items
"""


def format_report(topic: str, raw_research: str, llm: ChatGoogleGenerativeAI) -> str:
    """Formats raw agent research into a structured QueryPilot report."""
    today = datetime.now().strftime("%B %d, %Y")
    title = f"Research Report: {topic.title()}"

    system = (
        REPORT_SYSTEM_PROMPT
        .replace("{TITLE}", title)
        .replace("{topic}", topic)
        .replace("{date}", today)
    )

    user_prompt = f"""
Convert the following research notes into a full QueryPilot report.

TOPIC: {topic}

RESEARCH NOTES:
{raw_research}

Generate the complete report now.
"""

    response = llm.invoke([
        SystemMessage(content=system),
        HumanMessage(content=user_prompt),
    ])
    return response.content


def report_to_plain_text(report_md: str) -> str:
    """Strips markdown formatting for plain-text download."""
    text = re.sub(r"<[^>]+>", "", report_md)
    text = re.sub(r"^#{1,3}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*",   r"\1", text)
    text = re.sub(r"^---+$", "-" * 40, text, flags=re.MULTILINE)
    return text


def extract_sections(report_md: str) -> dict:
    """Parses the markdown report into a {section_name: content} dict."""
    sections, current, buffer = {}, "cover", []
    for line in report_md.split("\n"):
        if line.startswith("## "):
            if buffer:
                sections[current] = "\n".join(buffer).strip()
            current, buffer = line[3:].strip(), []
        else:
            buffer.append(line)
    if buffer:
        sections[current] = "\n".join(buffer).strip()
    return sections
